FROM fenglc/pgadmin4

# user: pgadmin4@pgadmin.org
# password: admin
# pg_dump & postgresql all in  "/usr/bin"
# backup in "/var/lib/pgadmin/storage/pgadmin4"

#COPY ./pgadmin.db.tar.gz /tmp/pgadmin.db.tar.gz
#RUN mkdir -p /var/lib/pgadmin && \
#	tar xzf /tmp/pgadmin.db.tar.gz -O > /var/lib/pgadmin/pgadmin4.db && \
#	rm -rf /tmp/pgadmin.db.tar.gz

EXPOSE 5050
