version: '2'



services:

### Applications Code Container #############################

    applications:
      image: tianon/true
      # env_file: .env
      volumes:
        - ${DOCKER_APPLICATION}:/var/www


### Workspace Utilities Container ###########################
    workspace:
      build:
        context: ./workspace
        args:
          - PUID=${PUID}
          - PGID=${PGID}
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      tty: true
      networks:
        - frontend
        - backend


### PHP-FPM Container #######################################

    php-fpm:
      build:
        context: ./php-fpm
        args:
          - PUID=${PUID}
          - PGID=${PGID}
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${DOCKER_PHP_IDE_CONFIG}
      networks:
        - backend

### PHP Worker Container #####################################

    php-worker:
      build:
        context: ./php-worker
        args:
          - PUID=${PUID}
          - PGID=${PGID}
      volumes_from:
        - applications
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      networks:
        - backend


### NGINX Server Container ##################################

    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php-fpm
          - PHP_UPSTREAM_PORT=9000
          - PUID=${PUID}
          - PGID=${PGID}
      volumes_from:
        - applications
      volumes:
        - ${DOCKER_APPLICATION}/storage/logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend


### PostgreSQL Container ####################################

    database:
      build: ./postgres
      environment:
        - POSTGRES_DB=wellmax
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      networks:
        - backend


### Redis Container #########################################

    redis:
      build: ./redis
      networks:
        - backend


### RabbitMQ Container ######################################

    rabbitmq:
      build: ./rabbitmq
      privileged: true
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=/
      depends_on:
        - php-fpm
      networks:
        - backend


### pgAdmin Container #######################################

    pgadmin:
      build: ./pgadmin
      environment:
        - DEFAULT_USER=postgres
        - DEFAULT_PASSWORD=postgres
      depends_on:
        - database
      networks:
        - frontend
        - backend


### Selenium Container ########################################

    selenium:
      build: ./selenium
      volumes:
        - /dev/shm:/dev/shm
      networks:
        - frontend

### Networks Setup ############################################

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"


### Volumes Setup #############################################

volumes:
  databse:
    driver: "local"
  pgadmin:
    driver: "local"
  memcached:
    driver: "local"
  redis:
    driver: "local"

