#
#--------------------------------------------------------------------------
# PHP Installation
#--------------------------------------------------------------------------
#

RUN docker-php-ext-install bcmath
RUN docker-php-ext-install exif
RUN docker-php-ext-install gmp
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install mcrypt
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install opcache
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-install pgsql
RUN docker-php-ext-install soap
RUN docker-php-ext-install tokenizer
RUN docker-php-ext-install xml
RUN docker-php-ext-install zip

RUN pecl update-channel
RUN pecl install -o -f redis     && docker-php-ext-enable redis
RUN pecl install -o -f xdebug    && docker-php-ext-enable xdebug
RUN pecl install -o -f swoole    && docker-php-ext-enable swoole
RUN pecl install -o -f amqp      && docker-php-ext-enable amqp
# RUN pecl install -o -f mongodb   && docker-php-ext-enable mongodb
RUN pecl install -o -f memcached && docker-php-ext-enable memcached

# imagemagick
RUN apt-get install -y libmagickwand-dev imagemagick
RUN pecl install -o -f imagick   && docker-php-ext-enable imagick

#####################################
# Human Language and Character Encoding Support:
#####################################

RUN docker-php-ext-configure intl && \
    docker-php-ext-install intl

#####################################
# LDAP:
#####################################

RUN docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
    docker-php-ext-install ldap

# Stop xDebug
RUN sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

