#
#--------------------------------------------------------------------------
# Image Setup
# $REF: $
#--------------------------------------------------------------------------
#
#

FROM php:7.1-fpm

COPY .      /bd_build
ADD ./bin /usr/sbin

#
#--------------------------------------------------------------------------
# Core Software's Installation
#--------------------------------------------------------------------------
#


RUN install_clean \
        wget curl \
        zip unzip \
        lsb-release \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev \
        libzip-dev libicu-dev \
        libldap2-dev \
        librabbitmq-dev \
        libgmp-dev \
        libxml2-dev \
        python-setuptools \
        libxslt-dev \
        libc-client-dev libkrb5-dev

# END Core Software's Installation  -------------

#
#--------------------------------------------------------------------------
# PHP Installation
#--------------------------------------------------------------------------
#
RUN echo "docker-php-ext-install"     && \
    pecl update-channels              && \
    docker-php-ext-configure gd      \
            --enable-gd-native-ttf   \
            --with-jpeg-dir=/usr/lib \
            --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd         && \
    docker-php-ext-install bcmath     && \
    docker-php-ext-install exif       && \
    docker-php-ext-install gmp        && \
    # docker-php-ext-install mbstring   && \
    docker-php-ext-install mcrypt     && \
    docker-php-ext-install opcache    && \
    docker-php-ext-install pcntl      && \
    # docker-php-ext-install pdo        && \
    docker-php-ext-install pdo_mysql  && \
    docker-php-ext-install pdo_pgsql  && \
    docker-php-ext-install pgsql      && \
    docker-php-ext-install sockets    && \
    # docker-php-ext-install tokenizer  && \
    # docker-php-ext-install xml        && \
    docker-php-ext-install xsl        && \
    docker-php-ext-install zip        && \
    docker-php-ext-install soap       && \
#
    pecl install -o -f amqp      && docker-php-ext-enable amqp      && \
    pecl install -o -f apcu      && docker-php-ext-enable apcu      && \
    pecl install -o -f memcached && docker-php-ext-enable memcached && \
    pecl install -o -f mongodb   && docker-php-ext-enable mongodb   && \
    pecl install -o -f redis     && docker-php-ext-enable redis     && \
    pecl install -o -f swoole    && docker-php-ext-enable swoole    && \
    pecl install -o -f xdebug    && docker-php-ext-enable xdebug    && \
        sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
#
    && docker-php-ext-configure intl            \
        && docker-php-ext-install intl          \
    && docker-php-ext-configure ldap            \
            --with-libdir=lib/x86_64-linux-gnu/ \
        && docker-php-ext-install ldap          \
    && docker-php-ext-configure imap            \
            --with-kerberos --with-imap-ssl      \
        && docker-php-ext-install imap

#RUN pecl install -o -f imagick              && docker-php-ext-enable imagick


# END PHP Installation --------------------------

ADD ./conf.d/*.ini /usr/local/etc/php/conf.d/
ADD ./php-fpm.d/*.conf /usr/local/etc/php-fpm.d/

RUN curl -s http://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

#
#--------------------------------------------------------------------------
# Clear code
#--------------------------------------------------------------------------
#


RUN apt-get autoremove -y \
    && apt-get autoclean -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* /var/tmp/*

WORKDIR /var/www
