#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#
#

FROM php:7.1-fpm

RUN mkdir -p /var/www 2>&1 >/dev/null

COPY .      /bd_build
ADD ./bin /usr/sbin

### <include> ../inc/Dockerfile-core
### <include> ../inc/Dockerfile-php

ADD ./conf.d/*.ini /usr/local/etc/php/conf.d/
ADD ./php-fpm.d/*.conf /usr/local/etc/php-fpm.d/

RUN curl -s http://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

### <include> ../inc/Dockerfile-clear

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
